<h2>Climate change</h2><br><br><br><br>

Climate change is a change in the statistical distribution of weather patterns when that change lasts for an extended period of time (i.e., decades to millions of years). Climate change may refer to a change in average weather conditions, or in the time variation of weather within the context of longer-term average conditions. Climate change is caused by factors such as biotic processes, variations in solar radiation received by Earth, plate tectonics, and volcanic eruptions. Certain human activities have been identified as primary causes of ongoing climate change, often referred to as global warming.[1] There is no general agreement in scientific, media or policy documents as to the precise term to be used to refer to anthropogenic forced change; either "global warming" or "climate change" may be used.<br><br><br>

Scientists actively work to understand past and future climate by using observations and theoretical models. A climate record—extending deep into the Earth's past—has been assembled, and continues to be built up, based on geological evidence from borehole temperature profiles, cores removed from deep accumulations of ice, floral and faunal records, glacial and periglacial processes, stable-isotope and other analyses of sediment layers, and records of past sea levels. More recent data are provided by the instrumental record. General circulation models, based on the physical sciences, are often used in theoretical approaches to match past climate data, make future projections, and link causes and effects in climate change.<br><br><br>

Factors that can shape climate are called climate forcings or "forcing mechanisms".[5] These can be either "internal" or "external". Internal forcing mechanisms are natural processes within the climate system itself (e.g., the thermohaline circulation). External forcing mechanisms can be either anthropogenic—caused by humans—(e.g. increased emissions of greenhouse gases and dust) or natural (e.g., changes in solar output, the earth's orbit, volcano eruptions).<br><br><br>

Physical evidence to observe climate change includes a range of parameters. Global records of surface temperature are available beginning from the mid-late 19th century. For earlier periods, most of the evidence is indirect—climatic changes are inferred from changes in proxies, indicators that reflect climate, such as ice cores,[6] dendrochronology, sea level change, and glacial geology. Other physical evidence includes arctic sea ice decline, cloud cover and precipitation, vegetation, animals and historical and archaeological evidence.<br><br><br><br><br><br>




The most general definition of climate change is a change in the statistical properties (principally its mean and spread)[7] of the climate system when considered over long periods of time, regardless of cause.[8] Accordingly, fluctuations over periods shorter than a few decades, such as El Niño, do not represent climate change.<br><br><br>

The term "climate change" is often used to refer specifically to anthropogenic climate change (also known as global warming). Anthropogenic climate change is caused by human activity, as opposed to changes in climate that may have resulted as part of Earth's natural processes.[2] In this sense, especially in the context of environmental policy, the term climate change has become synonymous with anthropogenic global warming. Within scientific journals, global warming refers to surface temperature increases while climate change includes global warming and everything else that increasing greenhouse gas levels affect.[3]<br><br><br>

A related term, "climatic change", was proposed by the World Meteorological Organization (WMO) in 1966 to encompass all forms of climatic variability on time-scales longer than 10 years, but regardless of cause. During the 1970s, the term climate change replaced climatic change to focus on anthropogenic causes, as it became clear that human activities had a potential to drastically alter the climate.[4] Climate change was incorporated in the title of the Intergovernmental Panel on Climate Change (IPCC) and the UN Framework Convention on Climate Change (UNFCCC). Climate change is now used as both a technical description of the process, as well as a noun used to describe the problem.[4]<br><br><br>
<br><br><br>
Causes<br><br><br>

On the broadest scale, the rate at which energy is received from the Sun and the rate at which it is lost to space determine the equilibrium temperature and climate of Earth. This energy is distributed around the globe by winds, ocean currents,[9][10] and other mechanisms to affect the climates of different regions.[11]<br><br><br>

Factors that can shape climate are called climate forcings or "forcing mechanisms".[5] These include processes such as variations in solar radiation, variations in the Earth's orbit, variations in the albedo or reflectivity of the continents, atmosphere, and oceans, mountain-building and continental drift and changes in greenhouse <br><br><br>gas concentrations. There are a variety of climate change feedbacks that can either amplify or diminish the initial forcing. Some parts of the climate system, such as the oceans and ice caps, respond more slowly in reaction to climate forcings, while others respond more quickly. There are also key threshold factors which when exceeded can produce rapid change.

Forcing mechanisms can be either "internal" or "external". Internal forcing mechanisms are natural processes within the climate system itself (e.g., the thermohaline circulation). External forcing mechanisms can be either anthropogenic (e.g. increased emissions of greenhouse gases and dust) or natural (e.g., changes in solar output, the earth's orbit, volcano eruptions).<br><br><br>

Whether the initial forcing mechanism is internal or external, the response of the climate system might be fast (e.g., a sudden cooling due to airborne volcanic ash reflecting sunlight), slow (e.g. thermal expansion of warming ocean water), or a combination (e.g., sudden loss of albedo in the Arctic Ocean as sea ice melts, followed by more gradual thermal expansion of the water). Therefore, the climate system can respond abruptly, but the full response to forcing mechanisms might not be fully developed for centuries or even longer.<br><br><br>
<br><br><br>
Internal forcing mechanisms<br><br><br>
Scientists generally define the five components of earth's climate system to include atmosphere, hydrosphere, cryosphere, lithosphere (restricted to the surface soils, rocks, and sediments), and biosphere.[12] Natural changes in the climate system ("internal forcings") result in internal "climate variability".[13] Examples include the type and distribution of species, and changes in ocean-atmosphere circulations.<br><br><br><br><br><br>