<h2>Geologic Time</h2><br><br><br>

The geologic time scale (GTS) is a system of chronological dating that relates geological strata (stratigraphy) to time. It is used by geologists, paleontologists, and other Earth scientists to describe the timing and relationships of events that have occurred during Earth's history. The table of geologic time spans, presented here, agree with the nomenclature, dates and standard color codes set forth by the International Commission on Stratigraphy (ICS).<br><br><br>


Evidence from radiometric dating indicates that Earth is about 4.54 billion years old.[3][4] The geology or deep time of Earth's past has been organized into various units according to events which took place. Different spans of time on the GTS are usually marked by corresponding changes in the composition of strata which indicate major geological or paleontological events, such as mass extinctions. For example, the boundary between the Cretaceous period and the Paleogene period is defined by the Cretaceous–Paleogene extinction event, which marked the demise of the non-avian dinosaurs and many other groups of life. Older time spans, which predate the reliable fossil record (before the Proterozoic eon), are defined by their absolute age.<br><br><br>

Geologic units from the same time but different parts of the world often look different and contain different fossils, so the same time-span was historically given different names in different locales. For example, in North America, the Lower Cambrian is called the Waucoban series that is then subdivided into zones based on succession of trilobites. In East Asia and Siberia, the same unit is split into Alexian, Atdabanian, and Botomian stages. A key aspect of the work of the International Commission on Stratigraphy is to reconcile this conflicting terminology and define universal horizons that can be used around the world.<br><br><br>

Some other planets and moons in the Solar System have sufficiently rigid structures to have preserved records of their own histories, for example, Venus, Mars and the Earth's Moon. Dominantly fluid planets, such as the gas giants, do not preserve their history in a comparable manner. Apart from the Late Heavy Bombardment, events on other planets probably had little direct influence on the Earth, and events on Earth had correspondingly little effect on those planets. Construction of a time scale that links the planets is, therefore, of only limited relevance to the Earth's time scale, except in a Solar System context. The existence, timing, and terrestrial effects of the Late Heavy Bombardment are still debated.<br><br><br>
<br><br><br>

Naming of geologic periods, eras and epochs<br><br><br>
Early work on developing the geologic time scale was dominated by British geologists, and the names of the geologic periods reflect that dominance. The "Cambrian", (the classical name for Wales) and the "Ordovician", and "Silurian", named after ancient Welsh tribes, were periods defined using stratigraphic sequences from Wales.[12]:113–114 The "Devonian" was named for the English county of Devon, and the name "Carboniferous" was an adaptation of "the Coal Measures", the old British geologists' term for the same set of strata. The "Permian" was named after Perm, Russia, because it was defined using strata in that region by Scottish geologist Roderick Murchison. However, some periods were defined by geologists from other countries. The "Triassic" was named in 1834 by a German geologist Friedrich Von Alberti from the three distinct layers (Latin trias meaning triad)—red beds, capped by chalk, followed by black shales—that are found throughout Germany and Northwest Europe, called the ‘Trias’. The "Jurassic" was named by a French geologist Alexandre Brongniart for the extensive marine limestone exposures of the Jura Mountains. The "Cretaceous" (from Latin creta meaning ‘chalk’) as a separate period was first defined by Belgian geologist Jean d'Omalius d'Halloy in 1822, using strata in the Paris basin[13] and named for the extensive beds of chalk (calcium carbonate deposited by the shells of marine invertebrates) found in Western Europe.<br><br><br>

British geologists were also responsible for the grouping of periods into eras and the subdivision of the Tertiary and Quaternary periods into epochs. In 1841 John Phillips published the first global geologic time scale based on the types of fossils found in each era. Phillips' scale helped standardize the use of terms like Paleozoic ("old life") which he extended to cover a larger period than it had in previous usage, and Mesozoic ("middle life") which he invented.<br><br><br>

Dating of time scales<br><br><br>
Main article: Chronological dating<br><br><br>
When William Smith and Sir Charles Lyell first recognized that rock strata represented successive time periods, time scales could be estimated only very imprecisely since estimates of rates of change were uncertain. While creationists had been proposing dates of around six or seven thousand years for the age of Earth based on the Bible, early geologists were suggesting millions of years for geologic periods, and some were even suggesting a virtually infinite age for Earth.[citation needed] Geologists and paleontologists constructed the geologic table based on the relative positions of different strata and fossils, and estimated the time scales based on studying rates of various kinds of weathering, erosion, sedimentation, and lithification. Until the discovery of radioactivity in 1896 and the development of its geological applications through radiometric dating during the first half of the 20th century, the ages of various rock strata and the age of Earth were the subject of considerable debate.<br><br><br>

The first geologic time scale that included absolute dates was published in 1913 by the British geologist Arthur Holmes.[15] He greatly furthered the newly created discipline of geochronology and published the world-renowned book The Age of the Earth in which he estimated Earth's age to be at least 1.6 billion years.<br><br><br>

In 1977, the Global Commission on Stratigraphy (now the International Commission on Stratigraphy) began to define global references known as GSSP (Global Boundary Stratotype Sections and Points) for geologic periods and faunal stages. The commission's most recent work is described in the 2004 geologic time scale of Gradstein et al.[17] A UML model for how the timescale is structured, relating it to the GSSP, is also available.<br><br><br>

The Anthropocene<br><br><br>
Popular culture and a growing number[citation needed] of scientists use the term "Anthropocene" informally to label the current epoch in which we are living. The term was coined by Paul Crutzen and Eugene Stoermer in 2000 to describe the current time, in which humans have had an enormous impact on the environment. It has evolved to describe an "epoch" starting some time in the past and on the whole defined by anthropogenic carbon emissions and production and consumption of plastic goods that are left in the ground.<br><br><br>

Critics of this term say that the term should not be used because it is difficult, if not nearly impossible, to define a specific time when humans started influencing the rock strata—defining the start of an epoch.[20] Others say that humans have not even started to leave their biggest impact on Earth, and therefore the Anthropocene has not even started yet.<br><br><br>

The ICS has not officially approved the term as of September 2015.[21] The Anthropocene Working Group met in Oslo in April 2016 to consolidate evidence supporting the argument for the Anthropocene as a true geologic epoch.[21] Evidence was evaluated and the group voted to recommend "Anthropocene" as the new geological age in August 2016.[22] Should the International Commission on Stratigraphy approve the recommendation, the proposal to adopt the term will have to be ratified by the International Union of Geological Sciences before its formal adoption as part of the geologic time scale.<br><br><br>
<br><br><br>
Table of geologic time<br><br><br><br><br><br>
The following table summarizes the major events and characteristics of the periods of time making up the geologic time scale. This table is arranged with the most recent geologic periods at the top, and the most ancient at the bottom. The height of each table entry does not correspond to the duration of each subdivision of time.<br><br><br>

The content of the table is based on the current official geologic time scale of the International Commission on Stratigraphy,[1] with the epoch names altered to the early/late format from lower/upper as recommended by the ICS when dealing with chronostratigraphy.<br><br><br><br><br><br>