<h2>Soil Mineralogy</h2><br><br><br><br>



Soil Mineralogy is a mixture of chemistry, materials science, physics and geology.<br><br><br>
Mineralogy[n 1] is a subject of geology specializing in the scientific study of the chemistry, crystal structure, and physical (including optical) properties of minerals and mineralized artifacts. Specific studies within mineralogy include the processes of mineral origin and formation, classification of minerals, their geographical distribution, as well as their utilization.<br><br><br>
<br><br><br>

Page from Treatise on mineralogy by Friedrich Mohs (1825)<br><br><br>

The Moon Mineralogy Mapper, a spectrometer that mapped the lunar surface<br><br><br>
Main article: History of mineralogy
Early writing on mineralogy, especially on gemstones, comes from ancient Babylonia, the ancient Greco-Roman world, ancient and medieval China, and Sanskrit texts from ancient India and the ancient Islamic World.[4] Books on the subject included the Naturalis Historia of Pliny the Elder, which not only described many different minerals but also explained many of their properties, and Kitab al Jawahir (Book of Precious Stones) by Persian scientist Al Biruni. The German Renaissance specialist Georgius Agricola wrote works such as De re metallica (On Metals, 1556) and De Natura Fossilium (On the Nature of Rocks, 1546) which began the scientific approach to the subject. Systematic scientific studies of minerals and rocks developed in post-Renaissance Europe.[4] The modern study of mineralogy was founded on the principles of crystallography (the origins of geometric crystallography, itself, can be traced back to the mineralogy practiced in the eighteenth and nineteenth centuries) and to the microscopic study of rock sections with the invention of the microscope in the 17th century.<br><br><br>

Nicholas Steno first observed the law of constancy of interfacial angles (also known as the first law of crystallography) in quartz crystals in 1669.[5]:4 This was later generalized and established experimentally by Jean-Baptiste L. Romé de l'Islee in 1783.[6] René Just Haüy, the "father of modern crystallography", showed that crystals are periodic and established that the orientations of crystal faces can be expressed in terms of rational numbers, as later encoded in the Miller indices.[5]:4 In 1814, Jöns Jacob Berzelius introduced a classification of minerals based on their chemistry rather than their crystal structure.[7] William Nicol developed the Nicol prism, which polarizes light, in 1827–1828 while studying fossilized wood; Henry Clifton Sorby showed that thin sections of minerals could be identified by their optical properties using a polarizing microscope.[5]:4[7]:15 James D. Dana published his first edition of A System of Mineralogy in 1837, and in a later edition introduced a chemical classification that is still the standard.[5]:4[7]:15 X-ray diffraction was demonstrated by Max von Laue in 1912, and developed into a tool for analyzing the crystal structure of minerals by the father/son team of William Henry Bragg and William Lawrence Bragg.<br><br><br>

More recently, driven by advances in experimental technique (such as neutron diffraction) and available computational power, the latter of which has enabled extremely accurate atomic-scale simulations of the behaviour of crystals, the science has branched out to consider more general problems in the fields of inorganic chemistry and solid-state physics. It, however, retains a focus on the crystal structures commonly encountered in rock-forming minerals (such as the perovskites, clay minerals and framework silicates). In particular, the field has made great advances in the understanding of the relationship between the atomic-scale structure of minerals and their function; in nature, prominent examples would be accurate measurement and prediction of the elastic properties of minerals, which has led to new insight into seismological behaviour of rocks and depth-related discontinuities in seismograms of the Earth's mantle. To this end, in their focus on the connection between atomic-scale phenomena and macroscopic properties, the mineral sciences (as they are now commonly known) display perhaps more of an overlap with materials science than any other discipline.<br><br><br>

Physical properties<br><br><br>

Calcite is a carbonate mineral (CaCO3) with a rhombohedral crystal structure.<br><br><br><br><br><br>

Aragonite is an orthorhombic polymorph of calcite.<br><br><br>
An initial step in identifying a mineral is to examine its physical properties, many of which can be measured on a hand sample. These can be classified into density (often given as specific gravity); measures of mechanical cohesion (hardness, tenacity, cleavage, fracture, parting); macroscopic visual properties (luster, color, streak, luminescence, diaphaneity); magnetic and electric properties; radioactivity and solubility in hydrogen chloride (HCl).[5]:97–113[8]:39–53<br><br><br>

Hardness is determined by comparison with other minerals. In the Mohs scale, a standard set of minerals are numbered in order of increasing hardness from 1 (talc) to 10 (diamond). A harder mineral will scratch a softer, so an unknown mineral can be placed in this scale by which minerals it scratches and which scratch it. A few minerals such as calcite and kyanite have a hardness that depends significantly on direction.[9]:254–255 Hardness can also be measured on an absolute scale using a sclerometer; compared to the absolute scale, the Mohs scale is nonlinear.[8]:52<br><br><br>

Tenacity refers to the way a mineral behaves when it is broken, crushed, bent or torn. A mineral can be brittle, malleable, sectile, ductile, flexible or elastic. An important influence on tenacity is the type of chemical bond (e.g., ionic or metallic).[9]:255–256 Of the other measures of mechanical cohesion, cleavage is the tendency to break along certain crystallographic planes. It is described by the quality (e.g., perfect or fair) and the orientation of the plane in crystallographic nomenclature. Parting is the tendency to break along planes of weakness due to pressure, twinning or exsolution. Where these two kinds of break do not occur, fracture is a less orderly form that may be conchoidal (having smooth curves resembling the interior of a shell), fibrous, splintery, hackly (jagged with sharp edges), or uneven.[9]:253–254<br><br><br>

If the mineral is well crystallized, it will also have a distinctive crystal habit (for example, hexagonal, columnar, botryoidal) that reflects the crystal structure or internal arrangement of atoms.[8]:40–41 It is also affected by crystal defects and twinning. Many crystals are polymorphic, having more than one possible crystal structure depending on factors such as pressure and temperature.[5]:66–68[8]:126<br><br><br>
<br><br><br>
Crystal structure<br><br><br>

The perovskite crystal structure. The most abundant mineral in the Earth, bridgmanite, has this structure.[10] Its chemical formula is (Mg,Fe)SiO3; the red spheres are oxygen, the blue spheres silicon and the green spheres magnesium or iron.<br><br><br>
Main article: Crystal structure<br><br><br>
See also: Crystallography
The crystal structure is the arrangement of atoms in a crystal. It is represented by a lattice of points which repeats a basic pattern, called a unit cell, in three dimensions. The lattice can be characterized by its symmetries and by the dimensions of the unit cell. These dimensions are represented by three Miller indices.[11]:91–92 The lattice remains unchanged by certain symmetry operations about any given point in the lattice: reflection, rotation, inversion, and rotary inversion, a combination of rotation and reflection. Together, they make up a mathematical object called a crystallographic point group or crystal class. There are 32 possible crystal classes. In addition, there are operations that displace all the points: translation, screw axis, and glide plane. In combination with the point symmetries, they form 230 possible space groups.[11]:125–126<br><br><br>

Most geology departments have X-ray powder diffraction equipment to analyze the crystal structures of minerals.[8]:54–55 X-rays have wavelengths that are the same order of magnitude as the distances between atoms. Diffraction, the constructive and destructive interference between waves scattered at different atoms, leads to distinctive patterns of high and low intensity that depend on the geometry of the crystal. In a sample that is ground to a powder, the X-rays sample a random distribution of all crystal orientations.[12] Powder diffraction can distinguish between minerals that may appear the same in a hand sample, for example quartz and its polymorphs tridymite and cristobalite.[8]:54<br><br><br>

Isomorphous minerals of different compositions have similar powder diffraction patterns, the main difference being in spacing and intensity of lines. For example, the NaCl (halite) crystal structure is space group Fm3m; this structure is shared by sylvite (KCl), periclase (MgO), bunsenite (NiO), galena (PbS), alabandite (MnS), chlorargyrite (AgCl), and osbornite (TiN).[9]:150–151<br><br><br>
<br><br><br>
Chemical elements<br><br><br>


Portable Micro-X-ray fluorescence machine<br><br><br>
A few minerals are chemical elements, including sulfur, copper, silver, and gold, but the vast majority are compounds. The classical method for identifying composition is wet chemical analysis, which involves dissolving a mineral in an acid such as hydrochloric acid (HCl). The elements in solution are then identified using colorimetry, volumetric analysis or gravimetric analysis.[9]:224–225<br><br><br>

Since 1960, most chemistry analysis is done using instruments. One of these, atomic absorption spectroscopy, is similar to wet chemistry in that the sample must still be dissolved, but it is much faster and cheaper. The solution is vaporized and its absorption spectrum is measured in the visible and ultraviolet range.[9]:225–226 Other techniques are X-ray fluorescence, electron microprobe analysis and optical emission spectrography.[9]:227–232<br><br><br><br><br><br>