<h2>Elasticity</h2><br><br><br>

<br><br><br>

In Physics, elasticity (from Greek ἐλαστός "ductible") is the ability of a body to resist a distorting influence and to return to its original size and shape when that influence or force is removed. Solid objects will deform when adequate forces are applied to them. If the material is elastic, the object will return to its initial shape and size when these forces are removed.<br><br><br>

The physical reasons for elastic behavior can be quite different for different materials. In metals, the atomic lattice changes size and shape when forces are applied (energy is added to the system). When forces are removed, the lattice goes back to the original lower energy state. For rubbers and other polymers, elasticity is caused by the stretching of polymer chains when forces are applied.<br><br><br>

Perfect elasticity is an approximation of the real world. The most elastic body in modern science found is quartz fibre[citation needed] which is not even a perfect elastic body. So perfect elastic body is an ideal concept only. Most materials which possess elasticity in practice remain purely elastic only up to very small deformations. In engineering, the amount of elasticity of a material is determined by two types of material parameter. The first type of material parameter is called a modulus, which measures the amount of force per unit area needed to achieve a given amount of deformation. The SI unit of modulus is the pascal (Pa). A higher modulus typically indicates that the material is harder to deform. The second type of parameter measures the elastic limit, the maximum stress that can arise in a material before the onset of permanent deformation. Its SI unit is also pascal (Pa).<br><br><br>

When describing the relative elasticities of two materials, both the modulus and the elastic limit have to be considered. Rubbers typically have a low modulus and tend to stretch a lot (that is, they have a high elastic limit) and so appear more elastic than metals (high modulus and low elastic limit) in everyday experience. Of two rubber materials with the same elastic limit, the one with a lower modulus will appear to be more elastic, which is however not correct. Actually elastic property of a material signifies it's strength to bear with the external load. Elasticity is defined as a phenomenon in which a body regains it's original sessions after removal of deforming force from it.<br><br><br>

<br><br><br><br><br><br>



When an elastic material is deformed due to an external force, it experiences internal resistance to the deformation and restores it to its original state if the external force is no longer applied. There are various elastic moduli, such as Young's modulus, the shear modulus, and the bulk modulus, all of which are measures of the inherent elastic properties of a material as a resistance to deformation under an applied load. The various moduli apply to different kinds of deformation. For instance, Young's modulus applies to extension/compression of a body, whereas the shear modulus applies to its shear.<br><br><br>

The elasticity of materials is described by a stress–strain curve, which shows the relation between stress (the average restorative internal force per unit area) and strain (the relative deformation).[2] The curve is generally nonlinear, but it can (by use of a Taylor series) be approximated as linear for sufficiently small deformations (in which higher-order terms are negligible). If the material is isotropic, the linearized stress–strain relationship is called Hooke's law, which is often presumed to apply up to the elastic limit for most metals or crystalline materials whereas nonlinear elasticity is generally required to model large deformations of rubbery materials even in the elastic range. For even higher stresses, materials exhibit plastic behavior, that is, they deform irreversibly and do not return to their original shape after stress is no longer applied.[3] For rubber-like materials such as elastomers, the slope of the stress–strain curve increases with stress, meaning that rubbers progressively become more difficult to stretch, while for most metals, the gradient decreases at very high stresses, meaning that they progressively become easier to stretch.[4] Elasticity is not exhibited only by solids; non-Newtonian fluids, such as viscoelastic fluids, will also exhibit elasticity in certain conditions quantified by the Deborah number. In response to a small, rapidly applied and removed strain, these fluids may deform and then return to their original shape. Under larger strains, or strains applied for longer periods of time, these fluids may start to flow like a viscous liquid.<br><br><br>

Because the elasticity of a material is described in terms of a stress–strain relation, it is essential that the terms stress and strain be defined without ambiguity. Typically, two types of relation are considered. The first type deals with materials that are elastic only for small strains. The second deals with materials that are not limited to small strains. Clearly, the second type of relation is more general in the sense that it must include the first type as a special case.<br><br><br>

For small strains, the measure of stress that is used is the Cauchy stress while the measure of strain that is used is the infinitesimal strain tensor; the resulting (predicted) material behavior is termed linear elasticity, which (for isotropic media) is called the generalized Hooke's law. Cauchy elastic materials and hypoelastic materials are models that extend Hooke's law to allow for the possibility of large rotations, large distortions, and intrinsic or induced anisotropy.<br><br><br>

For more general situations, any of a number of stress measures can be used, and it generally desired (but not required) that the elastic stress–strain relation be phrased in terms of a finite strain measure that is work conjugate to the selected stress measure, i.e., the time integral of the inner product of the stress measure with the rate of the strain measure should be equal to the change in internal energy for any adiabatic process that remains below the elastic limit.<br><br><br>
<br><br><br>
Linear elasticity<br><br><br>
Main article: Linear elasticity<br><br><br>
As noted above, for small deformations, most elastic materials such as springs exhibit linear elasticity and can be described by a linear relation between the stress and strain. This relationship is known as Hooke's law. A geometry-dependent version of the idea[5] was first formulated by Robert Hooke in 1675 as a Latin anagram, "ceiiinosssttuv". He published the answer in 1678: "Ut tensio, sic vis" meaning "As the extension, so the force",[6][7][8] a linear relationship commonly referred to as Hooke's law. This law can be stated as a relationship between tensile force F and corresponding extension displacement x,<br><br><br>
<br><br><br>
{\displaystyle F=kx,} {\displaystyle F=kx,}<br><br><br><br><br><br>
where k is a constant known as the rate or spring constant. It can also be stated as a relationship between stress σ and strain {\displaystyle \varepsilon } \varepsilon :<br><br><br>

<br><br><br>

