<h2>Inverting Operational Amplifier Configuration</h2><br><br><br><br>


In this Inverting Amplifier circuit the operational amplifier is connected with feedback to produce a closed loop operation. When dealing with operational amplifiers there are two very important rules to remember about inverting amplifiers, these are: “No current flows into the input terminal” and that “V1 always equals V2”. However, in real world op-amp circuits both of these rules are slightly broken.<br><br><br>

This is because the junction of the input and feedback signal ( X ) is at the same potential as the positive ( + ) input which is at zero volts or ground then, the junction is a “Virtual Earth”. Because of this virtual earth node the input resistance of the amplifier is equal to the value of the input resistor, Rin and the closed loop gain of the inverting amplifier can be set by the ratio of the two external resistors.<br><br><br>

We said above that there are two very important rules to remember about Inverting Amplifiers or any operational amplifier for that matter and these are.<br><br><br>

No Current Flows into the Input Terminals<br><br><br>
The Differential Input Voltage is Zero as V1 = V2 = 0 (Virtual Earth)<br><br><br>
Then by using these two rules we can derive the equation for calculating the closed-loop gain of an inverting amplifier, using first principles.<br><br><br>

Current ( i ) flows through the resistor network as shown.<br><br><br>

resistor feedback circuit<br><br><br>

inverting op-amp gain formula<br><br>

Then, the Closed-Loop Voltage Gain of an Inverting Amplifier is given as.<br><br>

inverting operational amplifier gain equation<br><br>
and this can be transposed to give Vout as:<br><br>

inverting operational amplifier gain<br><br>

op-amp linear output<br><br>
Linear Output<br><br>
<br>
The negative sign in the equation indicates an inversion of the output signal with respect to the input as it is 180o out of phase. This is due to the feedback being negative in value.<br><br><br>

The equation for the output voltage Vout also shows that the circuit is linear in nature for a fixed amplifier gain as Vout = Vin x Gain. This property can be very useful for converting a smaller sensor signal to a much larger voltage.<br><br><br>

Another useful application of an inverting amplifier is that of a “transresistance amplifier” circuit. A Transresistance Amplifier also known as a “transimpedance amplifier”, is basically a current-to-voltage converter (Current “in” and Voltage “out”). They can be used in low-power applications to convert a very small current generated by a photo-diode or photo-detecting device etc, into a usable output voltage which is proportional to the input current as shown.<br><br><br>

Transresistance Amplifier Circuit<br><br>
trans-resistance operational amplifier<br><br>

The simple light-activated circuit above, converts a current generated by the photo-diode into a voltage. The feedback resistor Rƒ sets the operating voltage point at the inverting input and controls the amount of output. The output voltage is given as Vout = Is x Rƒ. Therefore, the output voltage is proportional to the amount of input current generated by the photo-diode.<br><br>

Inverting Op-amp Example No1<br><br><br>
Find the closed loop gain of the following inverting amplifier circuit.<br><br>

inverting op-amp circuit<br><br>

Using the previously found formula for the gain of the circuit<br><br>

inverting op-amp gain<br><br>

we can now substitute the values of the resistors in the circuit as follows,<br><br><br>

Rin = 10kΩ  and  Rƒ = 100kΩ<br><br><br>

and the gain of the circuit is calculated as: -Rƒ/Rin = 100k/10k = -10<br><br><br>

Therefore, the closed loop gain of the inverting amplifier circuit above is given -10 or 20dB (20log(10)).<br><br><br>

Inverting Op-amp Example No2<br><br><br>
The gain of the original circuit is to be increased to 40 (32dB), find the new values of the resistors required.<br><br><br>

Assuming that the input resistor is to remain at the same value of 10KΩ, then by re-arranging the closed loop voltage gain formula we can find the new value required for the feedback resistor Rƒ.<br><br><br>

   Gain = Rƒ/Rin<br><br>

therefore,   Rƒ = Gain x Rin<br><br><br>

  Rƒ = 40 x 10,000<br><br><br>

  Rƒ = 400,000 or 400KΩ<br><br><br>

The new values of resistors required for the circuit to have a gain of 40 would be:<br><br><br>

 Rin = 10KΩ  and  Rƒ = 400KΩ<br><br><br>

The formula could also be rearranged to give a new value of Rin, keeping the same value of Rƒ.<br><br><br>

One final point to note about the Inverting Amplifier configuration for an operational amplifier, if the two resistors are of equal value, Rin = Rƒ  then the gain of the amplifier will be -1 producing a complementary form of the input voltage at its output as Vout = -Vin. This type of inverting amplifier configuration is generally called a Unity Gain Inverter of simply an Inverting Buffer.<br><br><br><br>

In the next tutorial about Operational Amplifiers, we will analyse the complement of the Inverting Amplifier operational amplifier circuit called the Non-inverting Amplifier that produces an output signal which is “in-phase” with the input.<br><br><br><br>

     
