<h2>Energy Conversion</h2><br><br><br><br><br>

Energy transformation, also termed as energy conversion, is the process of changing energy from one of its forms into another. In physics, energy is a quantity that provides the capacity to perform many works—think of lifting or warming an object. In addition to being convertible, energy is transferable to a different location or object, but it cannot be created or destroyed.<br><br><br>

Energy in many of its forms may be used in natural processes, or to provide some service to society such as heating, refrigeration, lighting or performing mechanical work to operate machines. For example, in order to heat your home, your furnace can burn fuel, whose chemical potential energy is thus converted into thermal energy, which is then transferred to your home's air in order to raise its temperature.<br><br><br>

In another example, an internal combustion engine burns gasoline to create pressure that pushes the pistons, thus performing work in order to accelerate your vehicle, ultimately converting the fuel's chemical energy to your vehicle's additional kinetic energy corresponding to its increase in speed.<br><br><br>


Conversions to thermal energy (thus raising the temperature) from other forms of energy, may occur with essentially 100% efficiency[citation needed] (many types %, such as when potential energy is converted to kinetic energy as an object falls in vacuum, or when an object orbits nearer or farther from another object, in space.<br><br><br><br>

Though, conversion of thermal energy to other forms, thus reducing the temperature of a system, has strict limitations, often keeping its efficiency much less than 100% (even when energy is not allowed to escape from the system). This is because thermal energy has already been partly spread out among many available states of a collection of microscopic particles constituting the system, which can have enormous numbers of possible combinations of momentum and position (these combinations are said to form a phase space). In such circumstances, a measure called entropy, or evening-out of energy distributions, dictates that future states of an isolated system must be of at least equal evenness in energy distribution. In other words, there is no way to concentrate energy without spreading out energy somewhere else.<br><br><br>

Thermal energy in equilibrium at a given temperature already represents the maximal evening-out of energy between all possible states. Such energy is sometimes considered "degraded energy," because it is not entirely convertible a "useful" form, i.e. one that can do more than just affect temperature. The second law of thermodynamics is a way of stating that, for this reason, thermal energy in a system may be converted to other kinds of energy with efficiencies approaching 100%, only if the entropy (even-ness or disorder) of the universe is increased by other means, to compensate for the decrease in entropy associated with the disappearance of the thermal energy and its entropy content. Otherwise, only a part of thermal energy may be converted to other kinds of energy (and thus, useful work), since the remainder of the heat must be reserved to be transferred to a thermal reservoir at a lower temperature, in such a way that the increase in Entropy for this process more than compensates for the entropy decrease associated with transformation of the rest of the heat into other types of energy...... Examples<br><br><br>

Transformation of kinetic energy of charged particles to electric energy<br><br><br>
In order to make energy transformation more efficient, it is desirable to avoid thermal conversion. For example, the efficiency of nuclear energy reactors, where the kinetic energy of the nuclei is first converted to thermal energy and then to electric energy, lies around 35%.[1][2] By direct conversion of kinetic energy to electric energy, i.e. by eliminating the intermediate thermal energy transformation, the efficiency of the energy transformation process can be dramatically improved.[3]<br><br><br>

History of energy transformation from the early universe<br><br><br>
Energy transformations in the universe over time are (generally) characterized by various kinds of energy which have been available since the Big Bang, later being "released" (that is, transformed to more active types of energy such as kinetic or radiant energy), when a triggering mechanism is available to do it.<br><br><br>

Release of energy from gravitational potential: A direct transformation of energy occurs when hydrogen produced in the Big Bang collects into structures such as planets, in a process during which part of the gravitational potential is to be converted directly into heat. In Jupiter, Saturn, and Neptune, for example, such heat from continued collapse of the planets' large gas atmospheres continues to drive most of the planets' weather systems, with atmospheric bands, winds, and powerful storms which are only partly powered by sunlight, however, on Uranus, little of this process occurs.<br><br><br>

On Earth, a significant portion of the heat output from the interior of the planet, estimated at a third to half of the total, is caused by the slow collapse of planetary materials to a smaller size, with the output of gravitationally driven heat.<br><br><br>

Release of energy from radioactive potential: Familiar examples of other such processes transforming energy from the Big Bang include nuclear decay, which releases energy that was originally "stored" in heavy isotopes, such as uranium and thorium. This energy was stored at the time of the nucleosynthesis of these elements, a process which ultimately uses the gravitational potential energy released from the gravitational collapse of Type II supernovae, to store energy in the creation of these heavy elements before they were incorporated into the Solar System and the Earth. Such energy locked into uranium is triggered for sudden-release in nuclear fission bombs, and similar stored energies in atomic nuclei are released spontaneously, during most types of radioactive decay. In such processes, heat from decay of these atoms of radioisotope in the core of the Earth is transformed immediately to heat. This heat in turn may lift mountains, via plate tectonics and orogenesis. This slow lifting of terrain thus represents a kind of gravitational potential energy storage of the heat energy. The stored potential energy may be released to active kinetic energy in landslides, after a triggering event. Earthquakes also release stored elastic potential energy in rocks, a kind of mechanical potential energy which has been produced ultimately from the same radioactive heat sources.<br><br><br>

